services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: medical-frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - medical-net